spring:
  data:
    redis:
      host: redis-13748.c322.us-east-1-2.ec2.cloud.redislabs.com
      port: 13748
      username: default
      password: rNCluEfLoH6BC5rF4YpDb9PH3scmD0Ok
  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always